- name: test my new module
  become: true
  become_method: su
  become_user: root
  
#  connection: local
  hosts: all
  vars:
    ansible_become_pass: password
  roles:
    - LIB 

  tasks:
  - name: run the new module
    my_new_test_module:
      name: 'hello'
      new: true
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
